export const COUNTRY_LIST = [
    { country: "Afrikaans", ISOCode: "af" },
    { country: "Albanian", ISOCode: "sq" },
    { country: "Amharic", ISOCode: "am" },
    { country: "Arabic", ISOCode: "ar" },
    { country: "Armenian", ISOCode: "hy" },
    { country: "Assamese", ISOCode: "as" },
    { country: "Aymara", ISOCode: "ay" },
    { country: "Azerbaijani", ISOCode: "az" },
    { country: "Bambara", ISOCode: "bm" },
    { country: "Basque", ISOCode: "eu" },
    { country: "Belarusian", ISOCode: "be" },
    { country: "Bengali", ISOCode: "bn" },
    { country: "Bhojpuri", ISOCode: "bho" },
    { country: "Bosnian", ISOCode: "bs" },
    { country: "Bulgarian", ISOCode: "bg" },
    { country: "Catalan", ISOCode: "ca" },
    { country: "Cebuano", ISOCode: "ceb" },
    { country: "Chinese (Simplified)", ISOCode: "zh-CN or zh (BCP-47)" },
    { country: "Chinese (Traditional)", ISOCode: "zh-TW (BCP-47)" },
    { country: "Corsican", ISOCode: "co" },
    { country: "Croatian", ISOCode: "hr" },
    { country: "Czech", ISOCode: "cs" },
    { country: "Danish", ISOCode: "da" },
    { country: "Dhivehi", ISOCode: "dv" },
    { country: "Dogri", ISOCode: "doi" },
    { country: "Dutch", ISOCode: "nl" },
    { country: "English", ISOCode: "en" },
    { country: "Esperanto", ISOCode: "eo" },
    { country: "Estonian", ISOCode: "et" },
    { country: "Ewe", ISOCode: "ee" },
    { country: "Filipino (Tagalog)", ISOCode: "fil" },
    { country: "Finnish", ISOCode: "fi" },
    { country: "French", ISOCode: "fr" },
    { country: "Frisian", ISOCode: "fy" },
    { country: "Galician", ISOCode: "gl" },
    { country: "Georgian", ISOCode: "ka" },
    { country: "German", ISOCode: "de" },
    { country: "Greek", ISOCode: "el" },
    { country: "Guarani", ISOCode: "gn" },
    { country: "Gujarati", ISOCode: "gu" },
    { country: "Haitian Creole", ISOCode: "ht" },
    { country: "Hausa", ISOCode: "ha" },
    { country: "Hawaiian", ISOCode: "haw" },
    { country: "Hebrew", ISOCode: "he or iw" },
    { country: "Hindi", ISOCode: "hi" },
    { country: "Hmong", ISOCode: "hmn" },
    { country: "Hungarian", ISOCode: "hu" },
    { country: "Icelandic", ISOCode: "is" },
    { country: "Igbo", ISOCode: "ig" },
    { country: "Ilocano", ISOCode: "ilo" },
    { country: "Indonesian", ISOCode: "id" },
    { country: "Irish", ISOCode: "ga" },
    { country: "Italian", ISOCode: "it" },
    { country: "Japanese", ISOCode: "ja" },
    { country: "Javanese", ISOCode: "jv or jw" },
    { country: "Kannada", ISOCode: "kn" },
    { country: "Kazakh", ISOCode: "kk" },
    { country: "Khmer", ISOCode: "km" },
    { country: "Kinyarwanda", ISOCode: "rw" },
    { country: "Konkani", ISOCode: "gom" },
    { country: "Korean", ISOCode: "ko" },
    { country: "Krio", ISOCode: "kri" },
    { country: "Kurdish", ISOCode: "ku" },
    { country: "Kurdish (Sorani)", ISOCode: "ckb" },
    { country: "Kyrgyz", ISOCode: "ky" },
    { country: "Lao", ISOCode: "lo" },
    { country: "Latin", ISOCode: "la" },
    { country: "Latvian", ISOCode: "lv" },
    { country: "Lingala", ISOCode: "ln" },
    { country: "Lithuanian", ISOCode: "lt" },
    { country: "Luganda", ISOCode: "lg" },
    { country: "Luxembourgish", ISOCode: "lb" },
    { country: "Macedonian", ISOCode: "mk" },
    { country: "Maithili", ISOCode: "mai" },
    { country: "Malagasy", ISOCode: "mg" },
    { country: "Malay", ISOCode: "ms" },
    { country: "Malayalam", ISOCode: "ml" },
    { country: "Maltese", ISOCode: "mt" },
    { country: "Maori", ISOCode: "mi" },
    { country: "Marathi", ISOCode: "mr" },
    { country: "Meiteilon (Manipuri)", ISOCode: "mni-Mtei" },
    { country: "Mizo", ISOCode: "lus" },
    { country: "Mongolian", ISOCode: "mn" },
    { country: "Myanmar (Burmese)", ISOCode: "my" },
    { country: "Nepali", ISOCode: "ne" },
    { country: "Norwegian", ISOCode: "no" },
    { country: "Nyanja (Chichewa)", ISOCode: "ny" },
    { country: "Odia (Oriya)", ISOCode: "or" },
    { country: "Oromo", ISOCode: "om" },
    { country: "Pashto", ISOCode: "ps" },
    { country: "Persian", ISOCode: "fa" },
    { country: "Polish", ISOCode: "pl" },
    { country: "Portuguese (Portugal, Brazil)", ISOCode: "pt" },
    { country: "Punjabi", ISOCode: "pa" },
    { country: "Quechua", ISOCode: "qu" },
    { country: "Romanian", ISOCode: "ro" },
    { country: "Russian", ISOCode: "ru" },
    { country: "Samoan", ISOCode: "sm" },
    { country: "Sanskrit", ISOCode: "sa" },
    { country: "Scots Gaelic", ISOCode: "gd" },
    { country: "Sepedi", ISOCode: "nso" },
    { country: "Serbian", ISOCode: "sr" },
    { country: "Sesotho", ISOCode: "st" },
    { country: "Shona", ISOCode: "sn" },
    { country: "Sindhi", ISOCode: "sd" },
    { country: "Sinhala (Sinhalese)", ISOCode: "si" },
    { country: "Slovak", ISOCode: "sk" },
    { country: "Slovenian", ISOCode: "sl" },
    { country: "Somali", ISOCode: "so" },
    { country: "Spanish", ISOCode: "es" },
    { country: "Sundanese", ISOCode: "su" },
    { country: "Swahili", ISOCode: "sw" },
    { country: "Swedish", ISOCode: "sv" },
    { country: "Tagalog (Filipino)", ISOCode: "tl" },
    { country: "Tajik", ISOCode: "tg" },
    { country: "Tamil", ISOCode: "ta" },
    { country: "Tatar", ISOCode: "tt" },
    { country: "Telugu", ISOCode: "te" },
    { country: "Thai", ISOCode: "th" },
    { country: "Tigrinya", ISOCode: "ti" },
    { country: "Tsonga", ISOCode: "ts" },
    { country: "Turkish", ISOCode: "tr" },
    { country: "Turkmen", ISOCode: "tk" },
    { country: "Twi (Akan)", ISOCode: "ak" },
    { country: "Ukrainian", ISOCode: "uk" },
    { country: "Urdu", ISOCode: "ur" },
    { country: "Uyghur", ISOCode: "ug" },
    { country: "Uzbek", ISOCode: "uz" },
    { country: "Vietnamese", ISOCode: "vi" },
    { country: "Welsh", ISOCode: "cy" },
    { country: "Xhosa", ISOCode: "xh" },
    { country: "Yiddish", ISOCode: "yi" },
    { country: "Yoruba", ISOCode: "yo" },
    { country: "Zulu", ISOCode: "zu" },
];

export const APP_TITLE = "GlobalTalk"
